import { useCallback,useEffect,useRef,useState } from "react";
import MovieGrid from "../components/MovieGrid";
import LoadingSpinner from "../components/LoadingSpinner";
import { getAnimeMovies } from "../services/movieAPI";
import { getAnimeSeries } from "../services/seriesAPI";
export default function Anime(){const [items,setItems]=useState([]),[page,setPage]=useState(0),[more,setMore]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState("");const trigger=useRef(null);const loadingRef=useRef(false);
 const load=useCallback(async(p=1,replace=false)=>{if(!replace&&loadingRef.current)return;loadingRef.current=true;setLoading(true);try{const [m,s]=await Promise.all([getAnimeMovies(p),getAnimeSeries(p)]);const mixed=[...(m.results||[]).map(x=>({...x,media_type:"movie"})),...(s.results||[]).map(x=>({...x,media_type:"tv"}))].sort((a,b)=>(b.popularity||0)-(a.popularity||0));setItems(x=>replace?mixed:[...x,...mixed]);setPage(p);setMore(p<Math.max(m.total_pages||1,s.total_pages||1))}catch(e){setError(e.message||"Unable to load anime")}finally{loadingRef.current=false;setLoading(false)}},[]);
 useEffect(()=>{load(1,true)},[load]);useEffect(()=>{if(!more||loading)return;const obs=new IntersectionObserver(e=>e[0].isIntersecting&&load(page+1),{rootMargin:"700px"});if(trigger.current)obs.observe(trigger.current);return()=>obs.disconnect()},[more,loading,page,load]);
 return <main className="container page"><section className="anime-banner"><span className="kicker">Animation catalog</span><h1 style={{margin:"10px 0 0",fontSize:"clamp(42px,6vw,70px)",letterSpacing:"-.05em"}}>Anime</h1><p style={{maxWidth:650,color:"#999",lineHeight:1.8}}>Animated movies and TV series in one dedicated catalog, sorted by popularity and loaded as you scroll.</p></section><section className="section">{error?<div className="empty">{error}</div>:loading&&!items.length?<div className="loader-wrap"><LoadingSpinner/></div>:<MovieGrid movies={items}/>}<div ref={trigger} style={{height:1}}/>{loading&&items.length?<div className="load-more"><LoadingSpinner/></div>:!more&&!loading?<div className="end-note">No more anime titles.</div>:null}</section></main>}
