import { useEffect,useState } from "react";
import MovieGrid from "../components/MovieGrid";
import LoadingSpinner from "../components/LoadingSpinner";
import { discoverMovies,getFilterMovie } from "../services/movieAPI";
import { discoverSeries,getSeriesGenres } from "../services/seriesAPI";
export default function Recommendation(){
 const [kind,setKind]=useState("both"),[genre,setGenre]=useState(""),[rating,setRating]=useState(""),[year,setYear]=useState(""),[genres,setGenres]=useState([]),[results,setResults]=useState([]),[loading,setLoading]=useState(false);
 useEffect(()=>{Promise.all([getFilterMovie(),getSeriesGenres()]).then(([m,s])=>{const map=new Map([...(m.genres||[]),...(s.genres||[])].map(g=>[g.id,g]));setGenres([...map.values()].sort((a,b)=>a.name.localeCompare(b.name)))}).catch(console.error)},[]);
 const suggest=async()=>{setLoading(true);try{const base={page:1,with_genres:genre,rating,year,sort_by:"vote_average.desc"};const calls=kind==="movie"?[discoverMovies(base)]:kind==="series"?[discoverSeries(base)]:[discoverMovies(base),discoverSeries(base)];const data=await Promise.all(calls);setResults(data.flatMap(d=>d.results||[]).map(x=>({...x,media_type:x.first_air_date?"tv":"movie"})).sort((a,b)=>(b.vote_average||0)-(a.vote_average||0)))}catch(e){console.error(e)}finally{setLoading(false)}};
 return <main className="container page"><section className="hero" style={{minHeight:"auto"}}><div className="hero-content"><span className="kicker">Personalized discovery</span><h1>What should you watch?</h1><p>Choose the kind of title you want, then narrow it down. No algorithmic astrology required.</p><div className="choice-grid">{[["both","Movie + Series","A mixed selection"],["movie","Movies","Only movies"],["series","Series","Only series"]].map(([v,l,d])=><button key={v} className={`choice ${kind===v?"selected":""}`} onClick={()=>setKind(v)}><strong>{l}</strong><small>{d}</small></button>)}</div><div className="recommendation-filter-gap"/><div className="filters"><select className="filter-input" value={genre} onChange={e=>setGenre(e.target.value)}><option value="">Any genre</option>{genres.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select className="filter-input" value={rating} onChange={e=>setRating(e.target.value)}><option value="">Any rating</option><option value="7">7+</option><option value="8">8+</option><option value="9">9+</option></select><select className="filter-input" value={year} onChange={e=>setYear(e.target.value)}><option value="">Any year</option>{Array.from({length:30},(_,i)=>new Date().getFullYear()-i).map(y=><option key={y} value={y}>{y}</option>)}</select></div><button className="btn btn-primary" style={{marginTop:12}} onClick={suggest} disabled={loading}>{loading?"Finding...":"Find suggestions"}</button></div></section><section className="section">{loading?<div className="loader-wrap"><LoadingSpinner/></div>:results.length?<><div className="section-head"><h2 className="section-title">Your suggestions</h2></div><MovieGrid movies={results}/></>:<div className="empty">Set your preferences and generate a fresh list.</div>}</section></main>;
}
