import { useCallback,useEffect,useRef,useState } from "react";
import { searchMovies } from "../services/movieAPI";
import MovieGrid from "../components/MovieGrid";
import LoadingSpinner from "../components/LoadingSpinner";
export default function Search(){
 const [query,setQuery]=useState(""),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[page,setPage]=useState(1),[totalPages,setTotalPages]=useState(0);const timer=useRef(null),trigger=useRef(null),loadingRef=useRef(false);
 useEffect(()=>{clearTimeout(timer.current);const q=query.trim();if(!q){setResults([]);setPage(1);setTotalPages(0);return}timer.current=setTimeout(async()=>{setLoading(true);loadingRef.current=true;try{const d=await searchMovies(q,1);setResults(d.results||[]);setPage(1);setTotalPages(d.total_pages||1)}catch(e){console.error(e);setResults([])}finally{loadingRef.current=false;setLoading(false)}},350);return()=>clearTimeout(timer.current)},[query]);
 const loadMore=useCallback(async()=>{if(loadingRef.current||!query.trim()||page>=totalPages)return;loadingRef.current=true;setLoading(true);try{const next=page+1,d=await searchMovies(query,next);setResults(x=>[...x,...(d.results||[])]);setPage(next);setTotalPages(d.total_pages||totalPages)}catch(e){console.error(e)}finally{loadingRef.current=false;setLoading(false)}},[query,page,totalPages]);
 useEffect(()=>{if(!query.trim()||page>=totalPages)return;const obs=new IntersectionObserver(e=>e[0].isIntersecting&&loadMore(),{rootMargin:"700px"});if(trigger.current)obs.observe(trigger.current);return()=>obs.disconnect()},[query,page,totalPages,loadMore]);
 return <main className="container page"><header className="page-head"><span className="kicker">Search</span><h1>Find your next watch.</h1><p>Search movies and series together. Results keep loading as you scroll.</p><div className="search-box"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles..." aria-label="Search titles"/><span className="search-icon">⌕</span></div></header>{query&&<div className="section-head"><h2 className="section-title">Results</h2><span className="section-eyebrow">{results.length} loaded</span></div>}{loading&&!results.length?<div className="loader-wrap"><LoadingSpinner/></div>:query&&!results.length?<div className="empty">No titles matched “{query}”.</div>:<MovieGrid movies={results}/>}<div ref={trigger} style={{height:1}}/>{loading&&results.length?<div className="load-more"><LoadingSpinner/></div>:query&&page<totalPages?<div className="load-more"><button className="btn btn-secondary" onClick={loadMore}>Load more</button></div>:null}</main>;
}
